<?xml version="1.0" encoding="utf-8"?>
<DataListDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataList.xsd" Version="1.2">
  <DataList Id="ace14a63-06fc-4c57-ab2c-11b6aaee635a" ConfigurationUri="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/74949bdd-1b22-4164-bf4d-5860443a6859" PlcIdentifier="1c0f4fbe-7bad-49ad-9309-191bf6c4542a" TargetAttributes="PlcNext,UserManagedComponentInstances,ResourceGlobalPorts" TargetVersion="0/2023.0.0" UICulture="en-US">
    <Datum Uuid="60820cc8-20aa-4bb5-a224-8395a8f21033">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="79c318f1-4ff8-4086-b19f-918f367d0b17" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PND_S1_PLC_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Higher level PLC in RUN</Comment>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pndpd1]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PND_S1_PLC_RUN</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="bc4a107a-e55b-4c68-a11d-6d2035675b00">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1b15b01a-7c03-48da-8904-22756b5ec17b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PND_S1_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Connection to Profinet-Controller</Comment>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pndpd2]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PND_S1_VALID_DATA_CYCLE</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="917cf956-0a3a-45c2-a6ed-da263dda0419">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="5d8a7862-8d4b-48e0-ac83-2cd8bfcf88f1" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PND_S1_OUTPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>IOP status of the higher-level control system</Comment>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pndpd3]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PND_S1_OUTPUT_STATUS_GOOD</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a209a227-b4ae-4f89-b117-cefab06711b6">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="7db07673-c697-4030-965f-5ce679d5a807" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PND_S1_INPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>IOC status of the higher-level control system</Comment>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pndpd4]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PND_S1_INPUT_STATUS_GOOD</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8dbc8ed7-8c19-4301-99a0-00e67dd8e6e5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="157dd4d7-bbba-41f8-8399-755e07d1e4fe" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PND_S1_DATA_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Process data length</Comment>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pndpd5]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PND_S1_DATA_LENGTH</Label>
        <Access>Read</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d06a73b0-5200-4a7b-af40-777b9c6c4988">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="02a4d9ed-2251-4650-8b57-b6720c6565e3" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PND_S1_OUTPUTS</Name>
        <Usage>Global</Usage>
        <DataType>PND_IO_512</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Output process data</Comment>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pndpd6]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PND_S1_OUTPUTS</Label>
        <Access>Write</Access>
        <DataType>Octetstring[512]</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="6eb19bc9-13a9-4c76-b730-3934da26af69">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6e14bc4c-7fdd-43f7-8958-fb92f92970ce" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PND_S1_INPUTS</Name>
        <Usage>Global</Usage>
        <DataType>PND_IO_512</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Input process data</Comment>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pndpd7]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PND_S1_INPUTS</Label>
        <Access>Read</Access>
        <DataType>Octetstring[512]</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="791ce647-5256-47ef-a09d-47e21888919b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="0bfcc730-96d9-49d5-b050-7952a74e7dde" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PND_IO_DRIVEN_BY_PLC</Name>
        <Usage>Global</Usage>
        <DataType>INT</DataType>
        <Address />
        <InitValue>INT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pndpd8]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PND_IO_DRIVEN_BY_PLC</Label>
        <Access>Read</Access>
        <DataType>Signed16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fc3dbac8-68ee-4b69-8dfa-af3865068602">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1b8c73a8-3a72-4bc2-a37b-ee4837774623" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=axiod0]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_HI</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="cc3efe60-117b-4329-9fec-dc443d087a3a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ab79d786-f005-4596-89dd-cbd7b14634f4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=axiod1]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_LOW</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b9017f1e-b818-41d2-92b4-da847ceb8e4e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ccf8c94a-eaed-4cca-b213-2075cb9aa07e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=axiod2]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_HI</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fb2f657a-e324-4b3e-8dd6-72a7690e8495">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="503a01a6-a237-4beb-a02a-123076161917" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=axiod3]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_LOW</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b369bab9-b215-4b9d-8cb4-c050b3c988e2">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e15023ae-15c2-4fce-bcac-2eabb18c206d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=axiod4]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_HI</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ae172107-e9d5-47fb-9024-f3890dc04129">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="33a00ce8-e5c7-4bc4-92a5-b906fce95070" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=axiod5]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_LOW</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ace91c1d-f571-42aa-b5df-d3109e4bc4bd">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="47d471d1-7a14-4139-865f-9ee80a957dab" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=axiod6]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PF</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="e6225c56-d3ac-4be5-9223-4a36bcf69e20">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="735844e7-610c-4c80-aa0d-3f1afa278ccd" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=axiod7]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_BUS</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fa590e2b-a97d-479d-9834-efa46d8cff86">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8587b87f-a7da-4ab5-b6ed-9bd7d17e1a18" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=axiod8]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RUN</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="595cf157-6efb-4713-aff5-17be64069fc4">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="7da1da36-eaa3-42f6-a024-7b7529952467" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=axiod9]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_ACT</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b05bbc3f-fff4-4eb1-ac2d-f33757a87b26">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="16091a25-5806-4fef-87a4-6fb2aa92f45f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=axiod10]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RDY</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b78f3351-ee33-4fe4-840e-5ce17ca51bba">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c5490dba-42ab-4f15-82e6-4b999a31d5cf" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=axiod11]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_SYSFAIL</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9ccf7456-9bd5-4865-a05c-49208b99d625">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ed6dc3b4-91a5-4872-a354-5a94fd8c89f2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>AXIO_DIAG_STATUS_REG_PW</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=axiod12]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PW</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="29155232-5fbf-46be-9bc4-d4f042709137">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="22bf8d3c-a16c-4056-94f2-7a697d8feab3" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdib1]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_HI</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="6fc5b638-b467-4d46-808d-5de3e5ef6840">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="212dd329-ac34-4f45-aa0b-1969c31a7fd6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pdib2]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_LOW</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2b42b0b3-4c9d-451a-a481-50cfb7047f49">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="03ee4557-8343-466c-89cf-ca281603af08" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pdib3]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_SYSFAIL</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2f72f6e9-bc58-4450-9dae-0d551faba330">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="5a38dd2e-bb80-4176-a67e-49dfe249ab16" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_WARN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pdib4]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_WARN</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1f67426a-004f-4946-90da-e0c17de43c1d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c349f972-0c06-4e82-a6e1-cb58f03fd91d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_QUAL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pdib5]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_QUAL</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7794b259-0588-48be-986c-79083726f39a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8ba391c1-6ae9-4c07-b4dc-654f5b1377b9" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_USER</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pdib6]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_USER</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a17e6ac7-9611-4215-8465-106242d46e35">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a3d046d6-304e-4c37-80f7-28392465fa94" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pdib7]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_PF</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="69bcc05e-a726-4423-a043-55bea9079bd5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="18038670-5a69-45ce-921e-4ac662a5fc83" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pdib8]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_BUS</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fc85b503-f506-45bb-b656-c791fdafd3e5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ba59c8e2-600d-470e-88ae-5bb630d7e4e2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_CTRL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pdib9]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_CTRL</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="bec88452-913b-45ca-805f-466dced7f18f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="25a2d5fe-969a-4e94-a72a-1cf23318f417" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_DTC</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pdib10]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_DTC</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ab67b2b0-1c38-4106-b0b3-6c7736d947ee">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c324470f-fd9d-4ce8-801e-90d8ee3fb7d7" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pdib11]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_RUN</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="42128b4a-ad77-480c-bfdd-a5a2906435bf">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="9a45dc86-8588-4e2d-bdba-2d8b6c14e55d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pdib12]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_ACT</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c484dbad-6fbd-46b7-b414-d6d59fe2f9ec">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b63a9a04-a122-44c7-abb3-0e5eb381ad50" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pdib13]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_STATUS_REG_RDY</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d26b4266-efd4-4624-8f6a-302dc008d7d7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="28711e29-0a74-4a8e-a36a-0a3db78376a9" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pdib14]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_PARAM_REG_HI</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1afc75e8-4cc2-4c1c-aa53-309d497e8197">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c7f4377f-06f2-4094-aa54-0b1c54a5ea7f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pdib15]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_PARAM_REG_LOW</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ee42f652-fca0-4c8c-9ad1-1c7ee7bcda81">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6ea98f70-b7b8-4546-981e-7fa520cd5d42" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pdib16]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_HI</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8885911e-fa41-4083-8014-2bb00ba2b2ba">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="254d5bcb-4595-4427-9a30-04742bdb1bbb" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IB_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pdib17]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_LOW</Label>
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="aac90765-3f73-4e56-bb5b-89769228b891">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6446a475-2ae2-4889-a12d-d8f423e2d6ce" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>ESM_DATA</Name>
        <Usage>Global</Usage>
        <DataType>ESM_DAT</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdesm1]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_1">
        <Label>ESM_DATA</Label>
        <Access>Read</Access>
        <DataType>ESM_DAT</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="17c03db1-428e-4900-b25f-d98211ff6d05">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="819d28c9-98ee-4a84-bd45-dd4bf454c9af" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>RTC</Name>
        <Usage>Global</Usage>
        <DataType>RTC_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pddi1]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_1">
        <Label>RTC</Label>
        <Access>Read</Access>
        <DataType>RTC_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="006bd368-9f70-4bac-8d19-0bbb5d7cb054">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c0b56960-d7bd-43eb-a086-cfd891ae0742" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>DEVICE_STATE</Name>
        <Usage>Global</Usage>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pddi2]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_1">
        <Label>DEVICE_STATE</Label>
        <Access>Read</Access>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="98aa2bf0-edc9-4b77-9116-ed64edb99360">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ee6247ea-35fd-4b8a-aab9-800cc9b92057" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>USER_PARTITION</Name>
        <Usage>Global</Usage>
        <DataType>PARTITION_INFO</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pddi4]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_1">
        <Label>USER_PARTITION</Label>
        <Access>Read</Access>
        <DataType>PARTITION_INFO</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="34b751ce-a2e1-42be-a7de-7328445d5b05">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6d89c59a-e24c-4747-bb6a-818e83f71e53" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PNIO_SYSTEM_BF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pncpd1]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PNIO_SYSTEM_BF</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="f782456c-e753-4692-8633-9e2743541589">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b8210fad-668c-473b-84a1-8f4ac50bbdeb" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PNIO_SYSTEM_SF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pncpd2]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PNIO_SYSTEM_SF</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="410c74fd-c8de-440e-842f-369c6847faff">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1d76a6f9-9372-4021-bd04-6b06b78573c3" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PNIO_MAINTENANCE_DEMANDED</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pncpd3]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PNIO_MAINTENANCE_DEMANDED</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c82a3f43-471c-45d6-b079-d904374b39cb">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1abe6315-1b86-4b0a-a500-22a311ebdc02" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PNIO_MAINTENANCE_REQUIRED</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pncpd4]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PNIO_MAINTENANCE_REQUIRED</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="048eb950-c11c-4190-bcfe-6ea7ba7f9041">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c67cb814-d99d-4045-9194-bf26ab6b84ba" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PNIO_CONFIG_STATUS</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pncpd5]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PNIO_CONFIG_STATUS</Label>
        <Access>Read</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="17c4f51c-2871-4ddb-bf7a-c0441561286c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="286852cb-34b3-4bdf-9de4-224ab8c5ccce" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PNIO_CONFIG_STATUS_ACTIVE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pncpd6]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PNIO_CONFIG_STATUS_ACTIVE</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4ebabb73-25cc-43ca-a930-c7e472eb11f6">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="efb1be35-44c0-45b5-96d5-54bdc701c291" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PNIO_CONFIG_STATUS_READY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pncpd7]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PNIO_CONFIG_STATUS_READY</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="725684c9-b462-4c45-9e9b-92e25e6e6c9a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fcc70f8b-6834-499e-bfc4-0612d66fc3bf" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PNIO_CONFIG_STATUS_CFG_FAULT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pncpd8]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PNIO_CONFIG_STATUS_CFG_FAULT</Label>
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="25069690-1108-4128-8d2f-54aa6f77f60f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="9f91aa30-ef58-443f-b619-2d4ce34580d2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PNIO_FORCE_FAILSAFE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pncpd9]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_4">
        <Label>PNIO_FORCE_FAILSAFE</Label>
        <Access>Write</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2c22f498-d79c-43ec-8443-7a664f09a765">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f88cb7b4-90a5-4168-98a4-8c70fcb16a7c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>IP_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <DataType>UINT</DataType>
        <Address>%MW1.30000</Address>
        <InitValue>UINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2f0cadba-be40-4b9d-a6ce-c05e1548c791">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d366548e-7210-4483-bb8e-6c7a5a427202" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>TLS_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <DataType>UINT</DataType>
        <Address>%MW1.30100</Address>
        <InitValue>UINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="e737efd4-af4b-49aa-968a-446fe05d06b8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="0fee08da-1fa0-4f6d-816b-04b3a8204a73" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>HMI_STATUS2</Name>
        <Usage>Global</Usage>
        <DataType>HMI_STATUS_TYPE2</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=hmipd001]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_3">
        <Label>HMI_STATUS2</Label>
        <Access>Read</Access>
        <DataType>HMI_STATUS_TYPE2</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3f75a77d-c941-4dcf-a83a-04379716d8d7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6aaaa377-026e-4688-ad54-dc68074a0260" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>HMI_CONTROL</Name>
        <Usage>Global</Usage>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=hmipd002]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_3">
        <Label>HMI_CONTROL</Label>
        <Access>Write</Access>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d002449c-3d75-427e-bde6-68dc14716b3f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b8b4da30-5d06-43bd-aebb-809aee254d95" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>EIPD_INPUTS</Name>
        <Usage>Global</Usage>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=eip001]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_7">
        <Label>EIPD_INPUTS</Label>
        <Access>Read</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="cdecba10-0b77-4440-8259-e7359c2b0016">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="baf9da7d-1034-4e5f-a4f0-b71334c31419" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>EIPD_OUTPUTS</Name>
        <Usage>Global</Usage>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=eip002]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_7">
        <Label>EIPD_OUTPUTS</Label>
        <Access>Write</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8084dbcc-177c-45b3-8dd0-db469601d07d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="7750d8b9-f418-4d9f-a513-a8efa497ec33" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>EIPD_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=eip003]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_7">
        <Label>EIPD_VALID_DATA_CYCLE</Label>
        <Access>Read</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="5a416de5-c42f-451b-b120-bcca1212f36e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d647d6e3-953f-45c1-a490-a4b3138f0d5b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>EIPD_PEER_IDLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=eip004]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_7">
        <Label>EIPD_PEER_IDLE</Label>
        <Access>Read</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="cc59a570-8935-42ec-9de7-715cd4be6203">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a5f4493a-209c-4129-8d97-72712ec8f1e5" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>EIPD_PEER_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=eip005]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_7">
        <Label>EIPD_PEER_RUN</Label>
        <Access>Read</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c7d753ba-e2b5-4da0-8569-002587cd38c1">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="3890d591-0855-4fac-b03f-9621a52b6219" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>EIPD_OUTPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=eip006]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_7">
        <Label>EIPD_OUTPUTS_LENGTH</Label>
        <Access>Read</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8a994752-326a-4cd9-adbb-9a0687133884">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="0e98385a-3406-400b-b086-5e8f36ac7b35" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>EIPD_INPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=eip007]" SourceId="1c0f4fbe-7bad-49ad-9309-191bf6c4542a.L7_7">
        <Label>EIPD_INPUTS_LENGTH</Label>
        <Access>Read</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ab2ac473-478a-44e1-8af7-0a39b37dbbbc">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="234e2f97-9cee-45c2-9a31-1df07231655d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe">
        <Name>PLC_CRC_PRJ</Name>
        <Usage>Global</Usage>
        <DataType>ULINT</DataType>
        <Address>%ML1.10000</Address>
        <InitValue>ULINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <RoleGroupList RoleTypeName="Variable">
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe" ObjectId="fb84caa8-36a3-47d9-8bf0-95ff0e8a7b24" DisplayName="Default" IsReadOnly="False" />
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/de66b83a-6bec-496f-a554-ea1ead086efe" ObjectId="971398c9-e054-4349-a1d9-e00a1840c9f4" DisplayName="System Variables" IsReadOnly="True">
        <RoleDatumUuid>60820cc8-20aa-4bb5-a224-8395a8f21033</RoleDatumUuid>
        <RoleDatumUuid>bc4a107a-e55b-4c68-a11d-6d2035675b00</RoleDatumUuid>
        <RoleDatumUuid>917cf956-0a3a-45c2-a6ed-da263dda0419</RoleDatumUuid>
        <RoleDatumUuid>a209a227-b4ae-4f89-b117-cefab06711b6</RoleDatumUuid>
        <RoleDatumUuid>8dbc8ed7-8c19-4301-99a0-00e67dd8e6e5</RoleDatumUuid>
        <RoleDatumUuid>d06a73b0-5200-4a7b-af40-777b9c6c4988</RoleDatumUuid>
        <RoleDatumUuid>6eb19bc9-13a9-4c76-b730-3934da26af69</RoleDatumUuid>
        <RoleDatumUuid>791ce647-5256-47ef-a09d-47e21888919b</RoleDatumUuid>
        <RoleDatumUuid>fc3dbac8-68ee-4b69-8dfa-af3865068602</RoleDatumUuid>
        <RoleDatumUuid>cc3efe60-117b-4329-9fec-dc443d087a3a</RoleDatumUuid>
        <RoleDatumUuid>b9017f1e-b818-41d2-92b4-da847ceb8e4e</RoleDatumUuid>
        <RoleDatumUuid>fb2f657a-e324-4b3e-8dd6-72a7690e8495</RoleDatumUuid>
        <RoleDatumUuid>b369bab9-b215-4b9d-8cb4-c050b3c988e2</RoleDatumUuid>
        <RoleDatumUuid>ae172107-e9d5-47fb-9024-f3890dc04129</RoleDatumUuid>
        <RoleDatumUuid>ace91c1d-f571-42aa-b5df-d3109e4bc4bd</RoleDatumUuid>
        <RoleDatumUuid>e6225c56-d3ac-4be5-9223-4a36bcf69e20</RoleDatumUuid>
        <RoleDatumUuid>fa590e2b-a97d-479d-9834-efa46d8cff86</RoleDatumUuid>
        <RoleDatumUuid>595cf157-6efb-4713-aff5-17be64069fc4</RoleDatumUuid>
        <RoleDatumUuid>b05bbc3f-fff4-4eb1-ac2d-f33757a87b26</RoleDatumUuid>
        <RoleDatumUuid>b78f3351-ee33-4fe4-840e-5ce17ca51bba</RoleDatumUuid>
        <RoleDatumUuid>9ccf7456-9bd5-4865-a05c-49208b99d625</RoleDatumUuid>
        <RoleDatumUuid>29155232-5fbf-46be-9bc4-d4f042709137</RoleDatumUuid>
        <RoleDatumUuid>6fc5b638-b467-4d46-808d-5de3e5ef6840</RoleDatumUuid>
        <RoleDatumUuid>2b42b0b3-4c9d-451a-a481-50cfb7047f49</RoleDatumUuid>
        <RoleDatumUuid>2f72f6e9-bc58-4450-9dae-0d551faba330</RoleDatumUuid>
        <RoleDatumUuid>1f67426a-004f-4946-90da-e0c17de43c1d</RoleDatumUuid>
        <RoleDatumUuid>7794b259-0588-48be-986c-79083726f39a</RoleDatumUuid>
        <RoleDatumUuid>a17e6ac7-9611-4215-8465-106242d46e35</RoleDatumUuid>
        <RoleDatumUuid>69bcc05e-a726-4423-a043-55bea9079bd5</RoleDatumUuid>
        <RoleDatumUuid>fc85b503-f506-45bb-b656-c791fdafd3e5</RoleDatumUuid>
        <RoleDatumUuid>bec88452-913b-45ca-805f-466dced7f18f</RoleDatumUuid>
        <RoleDatumUuid>ab67b2b0-1c38-4106-b0b3-6c7736d947ee</RoleDatumUuid>
        <RoleDatumUuid>42128b4a-ad77-480c-bfdd-a5a2906435bf</RoleDatumUuid>
        <RoleDatumUuid>c484dbad-6fbd-46b7-b414-d6d59fe2f9ec</RoleDatumUuid>
        <RoleDatumUuid>d26b4266-efd4-4624-8f6a-302dc008d7d7</RoleDatumUuid>
        <RoleDatumUuid>1afc75e8-4cc2-4c1c-aa53-309d497e8197</RoleDatumUuid>
        <RoleDatumUuid>ee42f652-fca0-4c8c-9ad1-1c7ee7bcda81</RoleDatumUuid>
        <RoleDatumUuid>8885911e-fa41-4083-8014-2bb00ba2b2ba</RoleDatumUuid>
        <RoleDatumUuid>aac90765-3f73-4e56-bb5b-89769228b891</RoleDatumUuid>
        <RoleDatumUuid>17c03db1-428e-4900-b25f-d98211ff6d05</RoleDatumUuid>
        <RoleDatumUuid>006bd368-9f70-4bac-8d19-0bbb5d7cb054</RoleDatumUuid>
        <RoleDatumUuid>98aa2bf0-edc9-4b77-9116-ed64edb99360</RoleDatumUuid>
        <RoleDatumUuid>34b751ce-a2e1-42be-a7de-7328445d5b05</RoleDatumUuid>
        <RoleDatumUuid>f782456c-e753-4692-8633-9e2743541589</RoleDatumUuid>
        <RoleDatumUuid>410c74fd-c8de-440e-842f-369c6847faff</RoleDatumUuid>
        <RoleDatumUuid>c82a3f43-471c-45d6-b079-d904374b39cb</RoleDatumUuid>
        <RoleDatumUuid>048eb950-c11c-4190-bcfe-6ea7ba7f9041</RoleDatumUuid>
        <RoleDatumUuid>17c4f51c-2871-4ddb-bf7a-c0441561286c</RoleDatumUuid>
        <RoleDatumUuid>4ebabb73-25cc-43ca-a930-c7e472eb11f6</RoleDatumUuid>
        <RoleDatumUuid>725684c9-b462-4c45-9e9b-92e25e6e6c9a</RoleDatumUuid>
        <RoleDatumUuid>25069690-1108-4128-8d2f-54aa6f77f60f</RoleDatumUuid>
        <RoleDatumUuid>2c22f498-d79c-43ec-8443-7a664f09a765</RoleDatumUuid>
        <RoleDatumUuid>2f0cadba-be40-4b9d-a6ce-c05e1548c791</RoleDatumUuid>
        <RoleDatumUuid>e737efd4-af4b-49aa-968a-446fe05d06b8</RoleDatumUuid>
        <RoleDatumUuid>3f75a77d-c941-4dcf-a83a-04379716d8d7</RoleDatumUuid>
        <RoleDatumUuid>d002449c-3d75-427e-bde6-68dc14716b3f</RoleDatumUuid>
        <RoleDatumUuid>cdecba10-0b77-4440-8259-e7359c2b0016</RoleDatumUuid>
        <RoleDatumUuid>8084dbcc-177c-45b3-8dd0-db469601d07d</RoleDatumUuid>
        <RoleDatumUuid>5a416de5-c42f-451b-b120-bcca1212f36e</RoleDatumUuid>
        <RoleDatumUuid>cc59a570-8935-42ec-9de7-715cd4be6203</RoleDatumUuid>
        <RoleDatumUuid>c7d753ba-e2b5-4da0-8569-002587cd38c1</RoleDatumUuid>
        <RoleDatumUuid>8a994752-326a-4cd9-adbb-9a0687133884</RoleDatumUuid>
        <RoleDatumUuid>ab2ac473-478a-44e1-8af7-0a39b37dbbbc</RoleDatumUuid>
      </RoleGroup>
    </RoleGroupList>
    <RoleGroupList RoleTypeName="SafetyVariable" />
  </DataList>
</DataListDocument>